name: CI/CD Pipeline for AI Artistic Style Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Pull the Docker image
      - name: Pull Docker Image
        run: |
          docker pull urmsandeep/ai-artistic-style-service:latest

      # Step 4: Run tests
      - name: Run Tests
        run: |
          docker run --rm -p 5001:5001 urmsandeep/ai-artistic-style-service:latest pytest tests/

      # Step 5: Deploy the service using Docker Compose
      - name: Deploy Service
        run: |
          docker-compose down
          docker-compose up -d

      # Step 6: Verify Deployment
      - name: Verify Deployment
        run: |
          sleep 5
          curl -X POST http://127.0.0.1:5001/styleTransfer -F "image=@test.jpg" --output styled_output.jpg

